export const distributors = [
    {"name":"All-Brand Supplies Dist.","city":"Medley","state":"Fl"},
    {"name":"Alliance Foods Ltd/Global","city":"Miami","state":"Fl"},
    {"name":"American Foods Llc","city":"Port Richey","state":"Fl"},
    {"name":"B & W Foods","city":"Bradenton","state":"Fl"},
    {"name":"Best Brands","city":"Tampa","state":"Fl"},
    {"name":"Busch Gardens Tampa","city":"Tampa","state":"Fl"},
    {"name":"Butler Foods Pensacola","city":"Cantonment","state":"Fl"},
    {"name":"Caribbean Basic Supplies","city":"Miami","state":"Fl"},
    {"name":"Cheney Brothers","city":"Punta Gorda","state":"Fl"},
    {"name":"Dania Restaurant Supply","city":"Dania","state":"Fl"},
    {"name":"Darden Direct Distribution Inc (Ddd","city":"Haines City","state":"Fl"},
    {"name":"Downtown Produce","city":"Melbourne","state":"Fl"},
    {"name":"Dunkin Donuts Southeast","city":"Groveland","state":"Fl"},
    {"name":"Florida Food Service","city":"Gainesville","state":"Fl"},
    {"name":"Food Parade","city":"Brooksville","state":"Fl"},
    {"name":"Food Supply, Inc.","city":"Daytona Beach","state":"Fl"},
    {"name":"Gordon Food Service - Plant City","city":"Plant City","state":"Fl"},
    {"name":"Hosp Services Unlimited","city":"Doral","state":"Fl"},
    {"name":"Jetblue Airways","city":"Orlando","state":"Fl"},
    {"name":"Mc Lane Foodservice Inc.","city":"Orlando","state":"Fl"},
    {"name":"P & L Foods Inc.","city":"Fort Myers","state":"Fl"},
    {"name":"PFG Florida","city":"Dover","state":"Fl"},
    {"name":"Princess Liquors Inc","city":"Port Saint Lucie","state":"Fl"},
    {"name":"Progressive Dist/American","city":"Opa Locka","state":"Fl"},
    {"name":"Quality Foods C/O Cheney","city":"Riviera Beach","state":"Fl"},
    {"name":"Quantum Distributors","city":"Winter Park","state":"Fl"},
    {"name":"Reinhart/Jacksonville","city":"Jacksonville","state":"Fl"},
    {"name":"Roma Foods Of Florida","city":"Orlando","state":"Fl"},
    {"name":"Seabreeze Seafood Dist.","city":"Jacksonville","state":"Fl"},
    {"name":"Seaworld Adventure Park","city":"Orlando","state":"Fl"},
    {"name":"Swf Food & Beverage Llc","city":"Fort Myers","state":"Fl"},
    {"name":"Sygma Florida","city":"Orlando","state":"Fl"},
    {"name":"Sysco Central Florida","city":"Ocoee","state":"Fl"},
    {"name":"Sysco International Food Group","city":"Plant City","state":"Fl"},
    {"name":"Sysco South Florida","city":"Medley","state":"Fl"},
    {"name":"Sysco Southeast Florida","city":"Riviera Beach","state":"Fl"},
    {"name":"Sysco West Coast Florida","city":"Palmetto","state":"Fl"},
    {"name":"Union Supply","city":"Jacksonville","state":"Fl"},
    {"name":"Usfs Boca Raton","city":"Boca Raton","state":"Fl"},
    {"name":"Usfs Lakeland","city":"Lakeland","state":"Fl"},
    {"name":"Usfs Port Orange (North Star)","city":"Port Orange","state":"Fl"},
    {"name":"Usfs Tampa","city":"Tampa","state":"Fl"},
    {"name":"Valencia","city":"Tampa","state":"Fl"},
    {"name":"Vi Finest Foods","city":"Miami","state":"Fl"},
    {"name":"Walt Disney World Co.","city":"Lake Buena Vista","state":"Fl"}
];

export const products = [{"sku":"MG-001","name":"Mello Green®","price":0.03},
    {"sku":"MG-002","name":"Mello Green® Classic","price":0.025},
    {"sku":"MG-003","name":"Diet Mello Green®","price":0.05},
    {"sku":"MG-004","name":"Mello Green® Zero","price":0.06},
    {"sku":"MG-005","name":"Cherry Mello Green®","price":0.04},
    {"sku":"MG-006","name":"Vanilla Mello Green®","price":0.04},
    {"sku":"MG-007","name":"Sour Mello Green®","price":0.04},
    {"sku":"MG-008","name":"Mister Doctor Mello Green®","price":0.08}];

export const sales = [];
